export const uiStuffTypes = {
  SET_CANDIDATE: 'SET_CANDIDATE',
  CLEAR_CANDIDATE: 'CLEAR_CANDIDATE',
};

export const createCandidateTypes = {
  REQUEST: 'CREATE_CANDIDATE_REQUEST',
  SUCCESS: 'CREATE_CANDIDATE_SUCCESS',
  FAILURE: 'CREATE_CANDIDATE_FAILURE',
};

export const getAllCandidatesTypes = {
  REQUEST: 'GET_ALL_CANDIDATES_REQUEST',
  SUCCESS: 'GET_ALL_CANDIDATES_SUCCESS',
  FAILURE: 'GET_ALL_CANDIDATES_FAILURE',
};

export const getCandidateByIdTypes = {
  REQUEST: 'GET_CANDIDATE_BY_ID_REQUEST',
  SUCCESS: 'GET_CANDIDATE_BY_ID_SUCCESS',
  FAILURE: 'GET_CANDIDATE_BY_ID_FAILURE',
}

export const updateCandidateTypes = {
  REQUEST: 'UPDATE_CANDIDATE_REQUEST',
  SUCCESS: 'UPDATE_CANDIDATE_SUCCESS',
  FAILURE: 'UPDATE_CANDIDATE_FAILURE',
};
