export const uiStuffTypes = {
  SET_APPLICATION: 'SET_APPLICATION',
  CLEAR_APPLICATION: 'CLEAR_APPLICATION',
  SHOW_MODAL: 'SHOW_APPLICATION_MODAL',
  HIDE_MODAL: 'HIDE_APPLICATION_MODAL',
};

export const getApplicationByIdTypes = {
  REQUEST: 'GET_APPLICATION_BY_ID_REQUEST',
  SUCCESS: 'GET_APPLICATION_BY_ID_SUCCESS',
  FAILURE: 'GET_APPLICATION_BY_ID_FAILURE',
}

