export const uiStuffTypes = {
  SET_TAG: 'SET_TAG',
  CLEAR_TAG: 'CLEAR_TAG',
  SHOW_MODAL: 'SHOW_TAG_MODAL',
  HIDE_MODAL: 'HIDE_TAG_MODAL',
};

export const createTagTypes = {
  REQUEST: 'CREATE_TAG_REQUEST',
  SUCCESS: 'CREATE_TAG_SUCCESS',
  FAILURE: 'CREATE_TAG_FAILURE',
};

export const getAllTagsTypes = {
  REQUEST: 'GET_ALL_TAGS_REQUEST',
  SUCCESS: 'GET_ALL_TAGS_SUCCESS',
  FAILURE: 'GET_ALL_TAGS_FAILURE',
};

export const getActiveTagsTypes = {
  REQUEST: 'GET_ACTIVE_TAGS_REQUEST',
  SUCCESS: 'GET_ACTIVE_TAGS_SUCCESS',
  FAILURE: 'GET_ACTIVE_TAGS_FAILURE',
};

export const updateTagTypes = {
  REQUEST: 'UPDATE_TAG_REQUEST',
  SUCCESS: 'UPDATE_TAG_SUCCESS',
  FAILURE: 'UPDATE_TAG_FAILURE',
};
