export const uiStuffTypes = {
  SET_TECHNOLOGY: 'SET_TECHNOLOGY',
  CLEAR_TECHNOLOGY: 'CLEAR_TECHNOLOGY',
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',
};

export const createTechnologyTypes = {
  REQUEST: 'CREATE_TECHNOLOGY_REQUEST',
  SUCCESS: 'CREATE_TECHNOLOGY_SUCCESS',
  FAILURE: 'CREATE_TECHNOLOGY_FAILURE',
};

export const getAllTechnologiesTypes = {
  REQUEST: 'GET_ALL_TECHNOLOGIES_REQUEST',
  SUCCESS: 'GET_ALL_TECHNOLOGIES_SUCCESS',
  FAILURE: 'GET_ALL_TECHNOLOGIES_FAILURE',
};

export const getTechnologyByIdTypes = {
  REQUEST: 'GET_TECHNOLOGY_BY_ID_REQUEST',
  SUCCESS: 'GET_TECHNOLOGY_BY_ID_SUCCESS',
  FAILURE: 'GET_TECHNOLOGY_BY_ID_FAILURE',
}

export const updateTechnologyTypes = {
  REQUEST: 'UPDATE_TECHNOLOGY_REQUEST',
  SUCCESS: 'UPDATE_TECHNOLOGY_SUCCESS',
  FAILURE: 'UPDATE_TECHNOLOGY_FAILURE',
};
