export const uiStuffTypes = {
  SET_USER: 'SET_USER',
  CLEAR_USER: 'CLEAR_USER',
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',
};

export const createUserTypes = {
  REQUEST: 'CREATE_USER_REQUEST',
  SUCCESS: 'CREATE_USER_SUCCESS',
  FAILURE: 'CREATE_USER_FAILURE',
};

export const getAllUsersTypes = {
  REQUEST: 'GET_ALL_USERS_REQUEST',
  SUCCESS: 'GET_ALL_USERS_SUCCESS',
  FAILURE: 'GET_ALL_USERS_FAILURE',
};

export const getCurrentUserTypes = {
  REQUEST: 'GET_CURRENT_USER_REQUEST',
  SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  FAILURE: 'GET_CURRENT_USER_FAILURE',
};

export const getUserByIdTypes = {
  REQUEST: 'GET_USER_BY_ID_REQUEST',
  SUCCESS: 'GET_USER_BY_ID_SUCCESS',
  FAILURE: 'GET_USER_BY_ID_FAILURE',
}

export const registerTypes = {
  REQUEST: 'REGISTER_REQUEST',
  SUCCESS: 'REGISTER_SUCCESS',
  FAILURE: 'REGISTER_FAILURE',
};

export const updateUserTypes = {
  REQUEST: 'UPDATE_USER_REQUEST',
  SUCCESS: 'UPDATE_USER_SUCCESS',
  FAILURE: 'UPDATE_USER_FAILURE',
};
