export const uiStuffTypes = {
  SET_PROCESS: 'SET_PROCESS',
  CLEAR_PROCESS: 'CLEAR_PROCESS',
  SHOW_MODAL: 'SHOW_PROCESS_MODAL',
  HIDE_MODAL: 'HIDE_PROCESS_MODAL',
};

export const createProcessTypes = {
  REQUEST: 'CREATE_PROCESS_REQUEST',
  SUCCESS: 'CREATE_PROCESS_SUCCESS',
  FAILURE: 'CREATE_PROCESS_FAILURE',
};

export const getAllProcessesTypes = {
  REQUEST: 'GET_ALL_PROCESSES_REQUEST',
  SUCCESS: 'GET_ALL_PROCESSES_SUCCESS',
  FAILURE: 'GET_ALL_PROCESSES_FAILURE',
};

export const getProcessByIdTypes = {
  REQUEST: 'GET_PROCESS_BY_ID_REQUEST',
  SUCCESS: 'GET_PROCESS_BY_ID_SUCCESS',
  FAILURE: 'GET_PROCESS_BY_ID_FAILURE',
}

export const updateProcessTypes = {
  REQUEST: 'UPDATE_PROCESS_REQUEST',
  SUCCESS: 'UPDATE_PROCESS_SUCCESS',
  FAILURE: 'UPDATE_PROCESS_FAILURE',
};
